version = 1

# REUSE.toml itself
[[annotations]]
path = ["REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# ci
[[annotations]]
path = [".github/**", ".obs/workflows.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# gitignore
[[annotations]]
path = [".gitignore", ".gitmodules"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# xml toml json conf yaml sh misc
[[annotations]]
path = ["**/*.toml", "**/*.json", "**/*conf", "**/*.yaml", "**/*.sh", "misc/**", ".clog.toml", "linglong.yaml", ".tx/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# debian
[[annotations]]
path = ["debian/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# cmake
[[annotations]]
path = ["cmake/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# rpm
[[annotations]]
path = ["rpm/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# Project file
[[annotations]]
path = ["**/*.pro", "**/*.prf", "**/*.pri", "**/*.qrc", "**/CMakeLists.txt", ".tx/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# docs
[[annotations]]
path = ["docs/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "LGPL-3.0-or-later"

# README
[[annotations]]
path = ["README*", "CHANGELOG.md", "INTRODUCTION.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

# translations (libimageviewer)
[[annotations]]
path = ["libimageviewer/translations/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

# src
[[annotations]]
path = ["src/**", "*.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

# translations
[[annotations]]
path = ["translations/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "LGPL-3.0-or-later"

# tests
[[annotations]]
path = ["tests/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

# patches
[[annotations]]
path = ["patches/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

# qt web
[[annotations]]
path = ["src/web/toSearchMd/common/qwebchannel.js", "src/web/toManual/qwebchannel.js", "src/web_dist/toManual/qwebchannel.js", "src/web_dist/toSearchMd/qwebchannel.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 The Qt Company Ltd.\\n2014 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Milian Wolff <milian.wolff@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# stub
[[annotations]]
path = ["tests/src/third-party/stub/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 coolxv"
SPDX-License-Identifier = "MIT"

# assets
[[annotations]]
path = ["manual-assets/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "LGPL-3.0-or-later"

# images
[[annotations]]
path = ["**/*.png", "**/*.jpg", "**/*.svg", "**/*.gif", "**/*.webp", "**/*.dci"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

# linglong
[[annotations]]
path = ["install_dep"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"
