.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 kongyunzhen <kongyunzhen@uniontech.com>,
.\"
.TH "deepin-manual" "1" "2021-3-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-manual \- manual for deepin application.
.SH SYNOPSIS
dman [AppName]
.SH DESCRIPTION
Deepin Manual binary.
.PP
Manual is designed to help users learn the operating system and its applications, providing specific instructions and function descriptions.
.SH OPTIONS
.PP 
-h   show help info
.PP
-v   show version
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-manual
.SH AUTHOR
.PP
.B deepin-manual
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT kongyunzhen@\:uniontech.com
Kong Yun Zhen
.ME
for the Debian Project (but may be used by others)
