.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 UnionTech Software Technology Co., Ltd.
.\"
.TH "dmanHelper" "1" "2021-3-29" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dmanHelper \- manual backend application.
.SH SYNOPSIS
dmanHelper [AppName]
.SH DESCRIPTION
Deepin Manual backend application.
.PP
dmanHelper is a backend application for Deepin Manual.
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-manual
.SH AUTHOR
.PP
.B dmanHelper
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT kongyunzhen@\:uniontech.com
Kong Yun Zhen
.ME
for the Debian Project (but may be used by others)
