/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.Manual.Open.xml -a manual_open_adapter -c ManualOpenAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MANUAL_OPEN_ADAPTER_H
#define MANUAL_OPEN_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.ManualOpenProxy
 */
class ManualOpenAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.ManualOpenProxy")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.ManualOpenProxy\">\n"
"    <method name=\"Open\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"app_name\"/>\n"
"    </method>\n"
"    <method name=\"OpenTitle\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"app_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"title_name\"/>\n"
"    </method>\n"
"    <method name=\"ShowManual\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"app_name\"/>\n"
"    </method>\n"
"    <method name=\"Search\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"keyword\"/>\n"
"    </method>\n"
"    <method name=\"FilesUpdate\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"filesList\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ManualOpenAdapter(QObject *parent);
    virtual ~ManualOpenAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void FilesUpdate(const QStringList &filesList);
    void Open(const QString &app_name);
    void OpenTitle(const QString &app_name, const QString &title_name);
    void Search(const QString &keyword);
    void ShowManual(const QString &app_name);
Q_SIGNALS: // SIGNALS
};

#endif
