/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.Manual.FilesUpdate.xml -a manual_filesupdate_adapter -c ManualFilesUpdateAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "manual_filesupdate_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ManualFilesUpdateAdapter
 */

ManualFilesUpdateAdapter::ManualFilesUpdateAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ManualFilesUpdateAdapter::~ManualFilesUpdateAdapter()
{
    // destructor
}

void ManualFilesUpdateAdapter::ActiveWindow()
{
    // handle method call local.ManualFilesUpdateProxy.ActiveWindow
    QMetaObject::invokeMethod(parent(), "ActiveWindow");
}

void ManualFilesUpdateAdapter::OnFilesUpdate(const QStringList &list)
{
    // handle method call local.ManualFilesUpdateProxy.OnFilesUpdate
    QMetaObject::invokeMethod(parent(), "OnFilesUpdate", Q_ARG(QStringList, list));
}

