/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.Manual.Search.xml -a manual_search_adapter -c
 * ManualSearchAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "manual_search_adapter.h"

#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QMetaObject>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ManualSearchAdapter
 */

ManualSearchAdapter::ManualSearchAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ManualSearchAdapter::~ManualSearchAdapter()
{
    // destructor
}

bool ManualSearchAdapter::ManualExists(const QString &in0)
{
    // handle method call com.deepin.Manual.Search.ManualExists
    bool out0;
    QMetaObject::invokeMethod(parent(), "ManualExists", Q_RETURN_ARG(bool, out0),
                              Q_ARG(QString, in0));
    return out0;
}

void ManualSearchAdapter::BindManual(const QString &app_name, const QString &winId)
{
    QMetaObject::invokeMethod(parent(), "BindManual", Q_ARG(QString, app_name),
                              Q_ARG(QString, winId));
}

void ManualSearchAdapter::CloseManual(const QString &app_name)
{
    QMetaObject::invokeMethod(parent(), "CloseManual", Q_ARG(QString, app_name));
}

bool ManualSearchAdapter::OnNewWindowOpen(const QString &data)
{
    bool out;
    QMetaObject::invokeMethod(parent(), "OnNewWindowOpen", Q_RETURN_ARG(bool, out),
                              Q_ARG(QString, data));
    return out;
}
