/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.Manual.Search.xml -a manual_search_adapter -c ManualSearchAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "manual_search_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ManualSearchAdapter
 */

ManualSearchAdapter::ManualSearchAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ManualSearchAdapter::~ManualSearchAdapter()
{
    // destructor
}

bool ManualSearchAdapter::ManualExists(const QString &in0)
{
    // handle method call com.deepin.Manual.Search.ManualExists
    bool out0;
    QMetaObject::invokeMethod(parent(), "ManualExists", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

void ManualSearchAdapter::Search(const QString &data)
{
    QMetaObject::invokeMethod(parent(), "Search", Q_ARG(QString, data));
}

